import '../models/employee.dart';

final List<Employee> dummyEmployees = [
  Employee(
    id: 'emp-001',
    name: 'I Made Lorem Ipsum Putra',
    position: 'Programer Coordinator',
    branch: 'BLiP - Head Office',
    email: 'loremipsum@gmail.com',
    phone: '+6287865679796',
    organizations: 'Technical & Operation',
    joinDate: '20 April 2020',
    birthDate: '21 Jul',
    photoUrl: 'https://i.pravatar.cc/300?img=68',
  ),
  Employee(
    id: 'emp-002',
    name: 'I Putu Lorem Ipsum Putri',
    position: 'Frontend Developer',
    branch: 'BLiP - Head Office',
    email: 'aswaspsum@gmail.com',
    phone: '+6287865680001',
    organizations: 'Technical & Operation',
    joinDate: '20 Juli 2020',
    birthDate: '22 Jul',
    photoUrl: 'https://i.pravatar.cc/300?img=5',
  ),
  Employee(
    id: 'emp-003',
    name: 'I Wayan Lorem Ipsum Putra',
    position: 'Backend Developer',
    branch: 'BLiP - Head Office',
    email: 'loremipsum@gmail.com',
    phone: '+6287665679706',
    organizations: 'Technical & Operation',
    joinDate: '20 Juni 2020',
    birthDate: '23 Jul',
    photoUrl: 'https://i.pravatar.cc/300?img=59',
  ),
  Employee(
    id: 'emp-004',
    name: 'I Ketut Lorem Ipsum Putra',
    position: 'Front Developer',
    branch: 'BLiP - Branch Office',
    email: 'lupagwidenya@gmail.com',
    phone: '+6287865669721',
    organizations: 'Technical & Operation',
    joinDate: '20 Agustus 2020',
    birthDate: '24 Jul',
    photoUrl: 'https://i.pravatar.cc/300?img=56',
  ),
  Employee(
    id: 'emp-005',
    name: 'I Nyoman Lorem Ipsum Putra',
    position: 'Backend Developer',
    branch: 'BLiP - Head Office',
    email: 'okeakukehabisanide@gmail.com',
    phone: '+6286865079706',
    organizations: 'Technical & Operation',
    joinDate: '20 September 2020',
    birthDate: '25 Jul',
    photoUrl: 'https://i.pravatar.cc/300?img=51',
  ),
];

final List<Employee> dummyAbsentEmployees =[
  Employee(
    id: 'abs-001',
    name: 'I Wayan Lorem Ipsum Putri',
    position: 'Backend Developer',
    branch: 'BLiP - Head Office',
    email: 'okeakukehabisanide@gmail.com',
    phone: '+6286865079706',
    organizations: 'Technical & Operation',
    joinDate: '20 September 2020',
    birthDate: '25 Jul',
    photoUrl: 'https://i.pravatar.cc/300?img=10',
  ),
  Employee(
    id: 'abs-002',
    name: 'I Gusti Lorem Ipsum Putri',
    position: 'Backend Developer',
    branch: 'BLiP - Head Office',
    email: 'okeakukehabisanide@gmail.com',
    phone: '+6286865079706',
    organizations: 'Technical & Operation',
    joinDate: '20 September 2020',
    birthDate: '25 Jul',
    photoUrl: 'https://i.pravatar.cc/300?img=7',
  ),
];